server:
  port: 8089
  error:
    include-message: always
spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  #  application:
  #    name: dtmember
  datasource:
    url: jdbc:postgresql://localhost:5445/dtmember
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
